export const themes = {
  "default-dark": {
    name: "default-dark",
    colors: {
      bg: "#0a0a0a",
      fg: "#d8d8d8",
      fgDim: "#888888",
      accent: "#00ff88",
      accentDim: "#008844",
      error: "#ff4444",
      warning: "#ffaa00",
      success: "#00ff88",
      link: "#66aaff",
      border: "#444444",
      borderFocus: "#00ff88",
    },
    font: {
      family: "JetBrains Mono, Cascadia Mono, Menlo, Consolas, monospace",
      size: 16,
      cellAspect: 0.6,
    },
    glyphs: {
      border: { tl: "┌", tr: "┐", bl: "└", br: "┘", h: "─", v: "│" },
      borderDouble: { tl: "╔", tr: "╗", bl: "╚", br: "╝", h: "═", v: "║" },
      borderRound: { tl: "╭", tr: "╮", bl: "╰", br: "╯", h: "─", v: "│" },
    },
  },
  "default-light": {
    name: "default-light",
    colors: {
      bg: "#fafafa",
      fg: "#202020",
      fgDim: "#707070",
      accent: "#0066cc",
      accentDim: "#003366",
      error: "#cc0000",
      warning: "#cc6600",
      success: "#006600",
      link: "#0044aa",
      border: "#bbbbbb",
      borderFocus: "#0066cc",
    },
    font: {
      family: "JetBrains Mono, Cascadia Mono, Menlo, Consolas, monospace",
      size: 16,
      cellAspect: 0.6,
    },
    glyphs: {
      border: { tl: "┌", tr: "┐", bl: "└", br: "┘", h: "─", v: "│" },
      borderDouble: { tl: "╔", tr: "╗", bl: "╚", br: "╝", h: "═", v: "║" },
      borderRound: { tl: "╭", tr: "╮", bl: "╰", br: "╯", h: "─", v: "│" },
    },
  },
  "crt-green": {
    name: "crt-green",
    colors: {
      bg: "#001100",
      fg: "#33ff66",
      fgDim: "#1a8833",
      accent: "#aaffaa",
      accentDim: "#558855",
      error: "#ff6666",
      warning: "#ffff66",
      success: "#88ff88",
      link: "#aaffff",
      border: "#226622",
      borderFocus: "#88ff88",
    },
    font: {
      family: "JetBrains Mono, monospace",
      size: 16,
      cellAspect: 0.6,
    },
    glyphs: {
      border: { tl: "┌", tr: "┐", bl: "└", br: "┘", h: "─", v: "│" },
      borderDouble: { tl: "╔", tr: "╗", bl: "╚", br: "╝", h: "═", v: "║" },
      borderRound: { tl: "╭", tr: "╮", bl: "╰", br: "╯", h: "─", v: "│" },
    },
  },
  "amber-terminal": {
    name: "amber-terminal",
    colors: {
      bg: "#1a0d00",
      fg: "#ffb000",
      fgDim: "#885500",
      accent: "#ffd866",
      accentDim: "#aa7700",
      error: "#ff6644",
      warning: "#ffee88",
      success: "#ccff88",
      link: "#ffddaa",
      border: "#553300",
      borderFocus: "#ffd866",
    },
    font: {
      family: "JetBrains Mono, monospace",
      size: 16,
      cellAspect: 0.6,
    },
    glyphs: {
      border: { tl: "┌", tr: "┐", bl: "└", br: "┘", h: "─", v: "│" },
      borderDouble: { tl: "╔", tr: "╗", bl: "╚", br: "╝", h: "═", v: "║" },
      borderRound: { tl: "╭", tr: "╮", bl: "╰", br: "╯", h: "─", v: "│" },
    },
  },
};
